name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:  # id of input
    description: 'Who to greet'
    required: true
  tag-name:
    description: "Name for the tag"
    required: true
outputs:
  ref: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  #entrypoint: ['entrypoint.sh']
  args:
    - ${{ inputs.token }}
    - ${{ inputs.tag-name }}