name: Build and Test GitHub actions
on: push

jobs:
  build_and_test:
    name: Build and test the GitHub Action
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0

    - name: Run the private action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag-name: v1